export const ROUTES = {
  home: "/",
  login: "/login",
  forgotPassword: "/forgot-password",
  register: "/register",
  dashboard: "/admin/dashboard",
  productDetail: "/products/:id",
  filterProduct: "/filter/:id",
  account: {
    profile: "/account/profile",
    editProfile: "/account/profile/edit",
    purchase: "/account/purchase",
    changePassword: "/account/change-password",
  },
  users: "/admin/users",
  categories: {
    root: "/admin/categories",
    new: "/admin/categories/new",
    edit: "/admin/categories/:id",
  },
  products: {
    root: "/admin/products",
    new: "/admin/products/new",
    edit: "/admin/products/:id",
  },
  cart: "/cart",
  checkout: "/checkout",
  search: "/search",
  orders: "/admin/orders",
  orderSuccess: "/order/success",
};
